---
name: Build
description: Checkout code, setup mkdocs, and build
runs:
  using: "composite"
  steps:
    - name: Setup build environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install build requirements
      run: pip install -r requirements.txt
    - name: Build docs
      run: mkdocs build
