---
name: "Build docs"
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install build requirements
        run: pip install -r requirements.txt
      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
